name: Intialise Terraform Code and Plan

#Workflow Triggers
on:
  push:
    branches:
      - master
      
##Environment Variables      
env:
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}
  GITHUB_TOKEN: ${{}}

#Define Jobs
jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read 

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_CREDENTIALS }}
        aws-region: ${{ vars.AWS_REGION }}

   
    - name: Initialise Terraform
      working-directory: ./terraform
      run: terraform init 


    - name: Terraform apply
      id: apply
      run: terraform apply --auto-approve


    

    

    